angular.module("app.modules",
    [
        "layout.module",
        "comum.module",
        "help.module",
        "usuario.module",
        "equipe.module",
        "projeto.module",
        "proposta.module",
        "app.toast.module",
        "app.dialog.module",
        "dashboard.module",
        "welcome.module"
    ]
);
