angular.module("app.modules",
    [
        "layout.module",
        "help.module",
        "usuario.module",
        "equipe.module",
        "proposta.module",
        "app.toast.module",
        "app.dialog.module",
        "dashboard.module"
    ]
);
